<a href="https://www.kaggle.com/code/ahmedfakhar123/ml-18-categorical-data-encoding?scriptVersionId=340132747" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---
# 🤖 ML 18 — Encoding Categorical Data for Machine Learning

### **Convert Text Features into Numbers with Label & Ordinal Encoding**

---

# 🚀 Introduction

Real-world datasets often contain **categorical (text) features** such as gender, education level, product category, and customer reviews. Since Machine Learning algorithms can only work with **numerical values**, these categories must be converted into numbers before training a model.

In this notebook, you'll learn two of the most commonly used encoding techniques:

* 🏷️ **Label Encoding**
* 📊 **Ordinal Encoding**

You'll also understand **when to use each technique**, **their advantages**, and **common mistakes to avoid** through practical examples.

By the end of this notebook, you'll be able to confidently prepare categorical features for Machine Learning models. 🚀

---
# 📦 Importing Required Libraries

We'll import the libraries required for data manipulation and categorical feature encoding.

In [1]:
import pandas as pd
import numpy as np

---
# 📖 1. Reading the Datasets

Let's load the datasets and explore the categorical features that we'll encode throughout this notebook.

In [2]:
df = pd.read_csv("/kaggle/input/datasets/ahmedfakhar123/customer-purchase-prediction-dataset/Customer_Encoding_Dataset.csv")
df

     age  gender     review    education purchased
0     38    Male    Average      Diploma        No
1     24  Female       Good     Bachelor       Yes
2     23  Female    Average      Diploma        No
3     21    Male  Excellent     Bachelor       Yes
4     21  Female       Poor      Diploma        No
..   ...     ...        ...          ...       ...
115   49  Female       Poor  High School        No
116   46  Female    Average      Diploma        No
117   38    Male       Good      Diploma       Yes
118   43    Male  Excellent      Diploma        No
119   36  Female    Average     Bachelor       Yes

[120 rows x 5 columns]

In [3]:
df1 = pd.read_csv("/kaggle/input/datasets/ahmedfakhar123/used-car-price-prediction-dataset/Used_Car_Prices.csv")
df1

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

---
# 🔍 2. Understanding the Dataset

Our dataset contains both numerical and categorical features.

| Feature   | Type                  |
| --------- | --------------------- |
| Age       | Numerical             |
| Gender    | Categorical (Nominal) |
| Review    | Categorical (Ordinal) |
| Education | Categorical (Ordinal) |
| Purchased | Target                |

---

## 💡 Before We Begin...

Before encoding categorical features, it's important to understand the different types of categorical data. The type of data determines which encoding technique should be used.

There are **two main types of categorical data**:

### 📊 Ordinal Data

Ordinal data has a **meaningful order or ranking** between categories.

**Examples:**
- Poor → Average → Good → Excellent
- School → Diploma → Bachelor → Master → PhD

✅ **Recommended Encoding:** **Ordinal Encoding**



### 🏷️ Nominal Data

Nominal data has **no natural order**. The categories are simply labels.

**Examples:**
- Male / Female
- Red / Blue / Green
- Karachi / Lahore / Islamabad

✅ **Recommended Encoding:** **Label Encoding** *(for binary categories like Male/Female)* or **One-Hot Encoding** *(for multiple categories like cities or colors).*



### 🔖 What is Label Encoding?

**Label Encoding** assigns a unique numerical label to each category.

**Example:**

| Gender | Encoded Value |
|---------|--------------:|
| Male | 1 |
| Female | 0 |

> **Note:** The assigned numbers do **not** represent any order or importance. They are simply unique identifiers.



Choosing the correct encoding technique is essential because using the wrong method can introduce unintended relationships between categories and negatively affect model performance.

---
# 📊 Step 1 — Ordinal Encoding

In this step, we'll apply **Ordinal Encoding** to categorical features that have a **natural order or ranking**.

Unlike nominal categories, ordinal categories represent a progression (e.g., *Poor → Average → Good → Excellent*), so preserving this order is important. **Ordinal Encoding** converts these categories into numerical values while maintaining their relative ranking.

In our dataset, the following features are ordinal:
- ⭐ **Review:** Poor → Average → Good → Excellent
- 🎓 **Education:** School → Diploma → Bachelor → Master → PhD

After encoding, Machine Learning models can understand the order of these categories and use them effectively during training.

## 1.1 Seperating Features and Target
We'll first separate the **ordinal features** from the **target variable** before applying the encoding.

In [4]:
X = df[["review", "education"]]
y = df.purchased

## 1.2 Splitting the Dataset

Next, we'll split the dataset into **training** and **testing** sets.

The encoder will be fitted **only on the training data** to prevent **data leakage**, and the learned mappings will then be applied to both the training and testing sets.

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

## 1.3 Applying Ordinal Encoding

Now we'll use **OrdinalEncoder** to convert the ordinal categories into numerical values.

Since our categories have a predefined order, we'll explicitly specify that order using the `categories` parameter.

In [6]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(
    categories=[
        ["Poor", "Average", "Good", "Excellent"],
        ["School", "High School", "Diploma", "Bachelor", "Master", "PhD"]
    ]
)

oe.fit(X_train)

X_train = oe.transform(X_train)

## 1.4 Encoded Features

After applying Ordinal Encoding, each category is replaced with its corresponding numerical value while preserving its order.

For example:

| Original | Encoded |
|----------|--------:|
| Poor | 0 |
| Average | 1 |
| Good | 2 |
| Excellent | 3 |

| Original | Encoded |
|----------|--------:|
| School | 0 |
| High School | 1 |
| Diploma | 2 |
| Bachelor | 3 |
| Master | 4 |
| PhD | 5 |

In [7]:
pd.DataFrame(X_train, columns=[["review", "education"]])

   review education
0     0.0       3.0
1     0.0       3.0
2     0.0       2.0
3     2.0       4.0
4     3.0       3.0
..    ...       ...
85    2.0       5.0
86    2.0       4.0
87    2.0       2.0
88    0.0       3.0
89    3.0       3.0

[90 rows x 2 columns]

## 1.5 Learned Categories

You can also inspect the category order learned by the encoder.

In [8]:
oe.categories_

[array(['Poor', 'Average', 'Good', 'Excellent'], dtype=object),
 array(['School', 'High School', 'Diploma', 'Bachelor', 'Master', 'PhD'],
       dtype=object)]

---
# 🎯 Step 2 — Label Encoder (Encoding the Target Variable)

Our target variable (`Purchased`) contains only two categories: **Yes** and **No**.

For binary target variables, **Label Encoding** is a simple and effective choice because it converts each class into a unique numerical label.

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

## 2.1 Learned Classes

Let's see how the target classes are mapped.

In [10]:
le.classes_

array(['No', 'Yes'], dtype=object)

The classes are encoded as:

- **No → 0**
- **Yes → 1**

This numerical representation allows Machine Learning algorithms to use the target variable during training.

---
# 🔤 Step 3 — One-Hot Encoding

In this step, we'll apply **One-Hot Encoding** to categorical features that have **no natural order or ranking**.

Unlike ordinal categories, nominal categories simply represent different groups (e.g., *Petrol, Diesel, CNG, Electric*) without any meaningful sequence. **One-Hot Encoding** converts each unique category into a separate binary (0 or 1) column, allowing Machine Learning models to process categorical data without assuming any order.

In our dataset, we'll apply One-Hot Encoding to the following nominal features:
- ⛽ **Fuel Type**
- 🚗 **Owner**

After encoding, each category becomes its own feature, making the dataset suitable for training Machine Learning models while preserving the categorical information.

## 3.1 OneHotEncoding using Pandas

In [11]:
pd.get_dummies(df1, columns=["fuel", "owner"])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## 3.2 K-1 OneHotEncoding

In [12]:
pd.get_dummies(df1, columns=["fuel", "owner"], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

## 3.3 OneHotEncoding using Sklearn

In [13]:
X = df1[["brand", "km_driven", "fuel", "owner"]]
y = df1.selling_price

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [15]:
X_train.head()

              brand  km_driven    fuel         owner
4313        Hyundai      40000  Petrol   First Owner
5178  Mercedes-Benz     120000  Petrol   First Owner
758         Hyundai      80000  Petrol  Second Owner
7117      Chevrolet     100000  Diesel   First Owner
2606         Maruti      77000  Diesel   First Owner

In [16]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

X_train_new = ohe.fit_transform(X_train[["fuel", "owner"]])
X_test_new = ohe.transform(X_test[["fuel", "owner"]])

In [17]:
X_train_new.shape

(6096, 7)

In [18]:
np.hstack((X_train[['brand','km_driven']].values, X_train_new))

array([['Hyundai', 40000, 0, ..., 0, 0, 0],
       ['Mercedes-Benz', 120000, 0, ..., 0, 0, 0],
       ['Hyundai', 80000, 0, ..., 1, 0, 0],
       ...,
       ['Hyundai', 90000, 0, ..., 1, 0, 0],
       ['Volkswagen', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 0, ..., 0, 0, 0]], dtype=object)

## 3.4 OneHotEncoding with Top Categories

In [19]:
counts = df1["brand"].value_counts()
threshold = 100

rare_brands = counts[counts <= threshold].index

df_encoded = pd.get_dummies(
    df1["brand"].replace(rare_brands, "Others"),
    dtype=int
)

In [20]:
df_encoded.sample(10)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Others,Renault,Skoda,Tata,Toyota,Volkswagen
7586,0,0,0,0,0,0,1,0,0,0,0,0,0
7693,0,0,0,0,0,0,0,0,0,0,0,1,0
4769,0,0,0,0,0,0,1,0,0,0,0,0,0
4983,0,0,0,0,0,0,1,0,0,0,0,0,0
3743,0,0,0,0,0,0,0,0,0,0,0,1,0
6984,0,0,0,0,0,1,0,0,0,0,0,0,0
1782,0,0,0,0,0,0,0,0,0,0,0,0,1
3470,0,0,0,1,0,0,0,0,0,0,0,0,0
4915,0,0,0,0,0,0,1,0,0,0,0,0,0
6889,0,0,0,0,1,0,0,0,0,0,0,0,0