<a href="https://www.kaggle.com/code/ahmedfakhar123/ml-24-knn-imputer-iterative-imputer?scriptVersionId=341162998" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---

# 🤖 ML 24 — KNN Imputer & Iterative Imputer

### **KNN & Iterative Methods for Smart Missing Value Imputation**

---

# 📖 Introduction

Missing values are common in real-world datasets. We previously used **Simple Imputer** with mean, median, and mode, but these methods don't consider relationships between data points.

In this notebook, we'll explore two advanced techniques:

* 🔹 **KNN Imputer** — uses similar observations to estimate missing values.
* 🔹 **Iterative Imputer** — predicts missing values using other features.
* 🔹 Compare both methods with traditional imputation techniques.

---

# 🤖 Step 1: What is KNN Imputer?

**KNN** stands for **K-Nearest Neighbors**.

KNN Imputer fills a missing value by finding the **K most similar observations** and using their values to estimate the missing value.

For example, if a person's salary is missing, KNN can find people with similar **age, experience, and other features** and use their salaries to estimate it.


### 💡 Simple idea

**Simple Imputer:**

> "Use the column's median."

**KNN Imputer:**

> "Find similar rows and use their values."

In [18]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer, SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [19]:
df = pd.read_csv('/kaggle/input/datasets/ahmedfakhar123/titanic-survival-dataset/Titanic_Survival_Dataset.csv')[
    ['Age','Pclass','Fare','Survived']
]
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [20]:
df.isnull().mean() * 100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [21]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

X_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [23]:
KNN = KNNImputer()

X_train_KNN = KNN.fit_transform(X_train)
X_test_KNN = KNN.transform(X_test)

In [24]:
model_KNN = LogisticRegression()

model_KNN.fit(X_train_KNN, y_train)

y_pred_KNN = model_KNN.predict(X_test_KNN)

print("Accuracy with KNNImputer:", accuracy_score(y_test, y_pred_KNN))

Accuracy with KNNImputer: 0.7039106145251397

In [25]:
simple = SimpleImputer()

X_train_simple = simple.fit_transform(X_train)
X_test_simple = simple.transform(X_test)

In [26]:
model_simple = LogisticRegression()

model_simple.fit(X_train_simple, y_train)

y_pred_simple = model.predict(X_test_simple)

print("Accuracy with KNNImputer:", accuracy_score(y_test, y_pred_simple))

Accuracy with KNNImputer: 0.6983240223463687