<a href="https://www.kaggle.com/code/ahmedfakhar123/ml-39-confusion-matrix-metrics?scriptVersionId=345073449" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---

# 🧠 ML 39 — Confusion Matrix & Metrics

---

In [1]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [2]:
df = pd.read_csv("/kaggle/input/datasets/mragpavank/heart-diseaseuci/heart.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [3]:
X = df.drop(columns=['target'])
y = df.target

In [4]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y, random_state=42)

In [5]:
clf1 = LogisticRegression(max_iter=1000)
clf2 = DecisionTreeClassifier()

In [6]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [7]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

# Accuracy Score

In [8]:
print(accuracy_score(y_test, y_pred1))
print(accuracy_score(y_test, y_pred2))

0.8947368421052632
0.7631578947368421

## How much accuracy is good?

## The problem with accuracy

# Confusion Matrix

In [9]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  30   5
1   3  38

In [10]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

    0   1
0  27   8
1  10  31

In [11]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
119             1                               1                         1
30              1                               1                         1
93              1                               1                         0
125             1                               1                         1
24              1                               1                         0
258             0                               0                         1
25              1                               1                         1
283             0                               1                         0
192             0                               0                         0
17              1                               1                         1

## Type 1 error

## Type 2 error

## When accuracy is misleading

Accuracy can be a misleading evaluation metric when dealing with imbalanced datasets, uneven error costs, or rare critical events, creating a false sense of model reliability

# Precision, Recall & F1 Score

In [12]:
print("For Logistic regression Model")

print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)

print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  30   5
1   3  38
--------------------------------------------------
Precision -  0.8837209302325582
Recall -  0.926829268292683
F1 score -  0.9047619047619048

In [13]:
print("For Decision Tree Model")

print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)

print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For Decision Tree Model
--------------------------------------------------
    0   1
0  27   8
1  10  31
--------------------------------------------------
Precision -  0.7948717948717948
Recall -  0.7560975609756098
F1 score -  0.775

In [14]:
print(precision_score(y_test,y_pred1,average=None))
print(precision_score(y_test,y_pred2,average=None))
print(recall_score(y_test,y_pred2,average=None))

[0.90909091 0.88372093]
[0.72972973 0.79487179]
[0.77142857 0.75609756]

In [15]:
print(precision_score(y_test,y_pred1,average='macro'))
print(precision_score(y_test,y_pred2,average='macro'))
print(recall_score(y_test,y_pred2,average='macro'))

0.8964059196617336
0.7623007623007623
0.7637630662020907

In [16]:
print(precision_score(y_test,y_pred1,average='weighted'))
print(precision_score(y_test,y_pred2,average='weighted'))
print(recall_score(y_test,y_pred2,average='weighted'))

0.8954044731278513
0.7648721596090017
0.7631578947368421

# Multiple

In [17]:
df1 = pd.read_csv('/kaggle/input/competitions/digit-recognizer/train.csv')
df1

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
X1 = df1.drop(columns=['label'])
y1 = df1.label

In [19]:
from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, random_state=2)

In [20]:
clf3 = LogisticRegression(max_iter=500)
clf4 = DecisionTreeClassifier()

clf3.fit(X_train1, y_train1)
clf4.fit(X_train1, y_train1)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [21]:
y_pred3 = clf3.predict(X_test1)
y_pred4 = clf4.predict(X_test1)