<a href="https://www.kaggle.com/code/ahmedfakhar123/ml-47-voting-ensemble-intuition-code?scriptVersionId=350085132" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---
# 🗳️ 👥 ML 47 — Voting Ensemble | Intuition & Code

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_classification

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.model_selection import cross_val_score

## Reading Data

In [2]:
df = pd.read_csv(
    '/kaggle/input/datasets/wasiqaliyasir/breast-cancer-dataset/Breast_cancer_dataset.csv',
    usecols=lambda column: column not in ["Unnamed: 32"]
)
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

## Label Encoding

In [3]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df.diagnosis = encoder.fit_transform(df.diagnosis)

df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

## Seperating Features & Target

In [4]:
X = df.drop(columns=['diagnosis'])
y = df.diagnosis

## Initializing Algorithms

In [5]:
clf1 = LogisticRegression(max_iter=250)
clf2 = RandomForestClassifier()
clf3 = GaussianNB()

## Setting Estimators

In [6]:
estimators = [('LogisticRegression', clf1), ('RandomForestClassifier', clf2), ('GaussianNB', clf3)]

In [7]:
for estimator in estimators:
    x = cross_val_score(estimator[1], X, y, cv=10, scoring='accuracy')
    print(estimator[0], ': ', np.round(np.mean(x), 2))

LogisticRegression :  0.92
RandomForestClassifier :  0.96
GaussianNB :  0.62

# Voting Ensemble Code

In [8]:
from sklearn.ensemble import VotingClassifier

## Hard Voting

In [9]:
vc = VotingClassifier(estimators=estimators)

x = cross_val_score(vc, X, y, cv=10, scoring='accuracy')
print(np.round(np.mean(x), 2))

0.93

## Soft Voting

In [10]:
vc = VotingClassifier(estimators=estimators, voting='soft')

x = cross_val_score(vc, X, y, cv=10, scoring='accuracy')
print(np.round(np.mean(x), 2))

0.95

## Weighted Voting

In [11]:
for i in range(1,4):
    for j in range(1,4):
        for k in range(1,4):
            vc = VotingClassifier(estimators=estimators, voting='soft', weights=[i, j, k])
            x = cross_val_score(vc, X, y, cv=10, scoring='accuracy')
            print(f"for i={i}, j={j}, k={k}", np.round(np.mean(x), 2))

for i=1, j=1, k=1 0.95
for i=1, j=1, k=2 0.92
for i=1, j=1, k=3 0.91
for i=1, j=2, k=1 0.95
for i=1, j=2, k=2 0.95
for i=1, j=2, k=3 0.94
for i=1, j=3, k=1 0.96
for i=1, j=3, k=2 0.96
for i=1, j=3, k=3 0.95
for i=2, j=1, k=1 0.93
for i=2, j=1, k=2 0.93
for i=2, j=1, k=3 0.91
for i=2, j=2, k=1 0.95
for i=2, j=2, k=2 0.95
for i=2, j=2, k=3 0.94
for i=2, j=3, k=1 0.95
for i=2, j=3, k=2 0.96
for i=2, j=3, k=3 0.95
for i=3, j=1, k=1 0.92
for i=3, j=1, k=2 0.92
for i=3, j=1, k=3 0.92
for i=3, j=2, k=1 0.93
for i=3, j=2, k=2 0.93
for i=3, j=2, k=3 0.94
for i=3, j=3, k=1 0.95
for i=3, j=3, k=2 0.95
for i=3, j=3, k=3 0.95

## Using Same Algorithm

In [12]:
X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=2)

In [13]:
svm1 = SVC(probability=True, kernel='poly', degree=1)
svm2 = SVC(probability=True, kernel='poly', degree=2)
svm3 = SVC(probability=True, kernel='poly', degree=3)
svm4 = SVC(probability=True, kernel='poly', degree=4)
svm5 = SVC(probability=True, kernel='poly', degree=5)

In [14]:
estimators = [('SVM1', svm1), ('SVM2', svm2), ('SVM3', svm3), ('SVM4', svm4), ('SVM5', svm5)]

In [15]:
for estimator in estimators:
    x = cross_val_score(estimator[1], X, y, cv=10, scoring='accuracy')
    print(estimator[0], np.round(np.mean(x), 2))

SVM1 0.85
SVM2 0.85
SVM3 0.89
SVM4 0.81
SVM5 0.86

In [16]:
vc1 = VotingClassifier(estimators=estimators, voting='soft')

x = cross_val_score(vc1, X, y, cv=10, scoring='accuracy')
print(np.round(np.mean(x), 2))

0.93